sap.ui.define([
    "sap/ui/model/json/JSONModel"
], function (JSONModel) {
    "use strict";

    // Comprehensive aircraft fleet data following SAP UI5 best practices
    // Using tail numbers from flight_data.csv (first 20 records)
    var aircraftFleetData = [
        {
            tailNumber: "SA8880",
            model: "Boeing 737-800",
            flightHoursSinceLastMaintenance: 125,
            engineTemperature: 485,
            vibrationLevel: 1.8,
            hydraulicPressure: 3000,
            brakeWearPercent: 25,
            oilParticleCount: 850,
            weatherStressIndex: 7.2,
            aircraftAgeYears: 8,
            flightCycles: 8920,
            mtbf: 450,
            lastFailureDate: "2023-11-15",
            lastFailureType: "Hydraulic",
            failureHistory: [
                { date: "2023-11-15", type: "Hydraulic", severity: "minor" },
                { date: "2023-08-22", type: "Engine", severity: "major" },
                { date: "2023-05-10", type: "Landing Gear", severity: "minor" }
            ],
            overallStatus: "normal",
            riskScore: 25.5,
            nextMaintenanceEstimate: "2025-06-15",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "KE2815",
            model: "Airbus A320",
            flightHoursSinceLastMaintenance: 890,
            engineTemperature: 512,
            vibrationLevel: 2.4,
            hydraulicPressure: 2850,
            brakeWearPercent: 67,
            oilParticleCount: 1250,
            weatherStressIndex: 8.9,
            aircraftAgeYears: 5,
            flightCycles: 6420,
            mtbf: 320,
            lastFailureDate: "2024-01-08",
            lastFailureType: "Engine",
            failureHistory: [
                { date: "2024-01-08", type: "Engine", severity: "critical" },
                { date: "2023-10-14", type: "Avionics", severity: "major" },
                { date: "2023-07-03", type: "Hydraulic", severity: "minor" }
            ],
            overallStatus: "critical",
            riskScore: 78.3,
            nextMaintenanceEstimate: "2025-03-12",
            alertStatus: "Critical",
            maintenanceStatus: "Overdue"
        },
        {
            tailNumber: "DL6343",
            model: "Boeing 777-300",
            flightHoursSinceLastMaintenance: 210,
            engineTemperature: 498,
            vibrationLevel: 1.2,
            hydraulicPressure: 3200,
            brakeWearPercent: 12,
            oilParticleCount: 650,
            weatherStressIndex: 5.1,
            aircraftAgeYears: 12,
            flightCycles: 11250,
            mtbf: 680,
            lastFailureDate: "2023-09-20",
            lastFailureType: "Landing Gear",
            failureHistory: [
                { date: "2023-09-20", type: "Landing Gear", severity: "minor" },
                { date: "2023-04-15", type: "Hydraulic", severity: "minor" }
            ],
            overallStatus: "normal",
            riskScore: 18.9,
            nextMaintenanceEstimate: "2025-12-10",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "QR5924",
            model: "Airbus A330",
            flightHoursSinceLastMaintenance: 450,
            engineTemperature: 545,
            vibrationLevel: 1.9,
            hydraulicPressure: 2650,
            brakeWearPercent: 88,
            oilParticleCount: 1450,
            weatherStressIndex: 9.7,
            aircraftAgeYears: 15,
            flightCycles: 16890,
            mtbf: 180,
            lastFailureDate: "2024-02-01",
            lastFailureType: "Brake System",
            failureHistory: [
                { date: "2024-02-01", type: "Brake System", severity: "critical" },
                { date: "2023-12-18", type: "Engine", severity: "major" },
                { date: "2023-09-05", type: "Hydraulic", severity: "major" },
                { date: "2023-06-12", type: "Avionics", severity: "minor" }
            ],
            overallStatus: "critical",
            riskScore: 89.1,
            nextMaintenanceEstimate: "2025-02-15",
            alertStatus: "Critical",
            maintenanceStatus: "Overdue"
        },
        {
            tailNumber: "AF1454",
            model: "Boeing 787-9",
            flightHoursSinceLastMaintenance: 95,
            engineTemperature: 475,
            vibrationLevel: 1.1,
            hydraulicPressure: 3100,
            brakeWearPercent: 18,
            oilParticleCount: 420,
            weatherStressIndex: 4.3,
            aircraftAgeYears: 3,
            flightCycles: 4230,
            mtbf: 720,
            lastFailureDate: null,
            lastFailureType: null,
            failureHistory: [],
            overallStatus: "normal",
            riskScore: 12.4,
            nextMaintenanceEstimate: "2025-11-20",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "ET4010",
            model: "Airbus A321",
            flightHoursSinceLastMaintenance: 820,
            engineTemperature: 501,
            vibrationLevel: 2.1,
            hydraulicPressure: 2950,
            brakeWearPercent: 45,
            oilParticleCount: 980,
            weatherStressIndex: 6.8,
            aircraftAgeYears: 7,
            flightCycles: 7650,
            mtbf: 380,
            lastFailureDate: "2023-12-03",
            lastFailureType: "Avionics",
            failureHistory: [
                { date: "2023-12-03", type: "Avionics", severity: "major" },
                { date: "2023-08-15", type: "Engine", severity: "minor" }
            ],
            overallStatus: "warning",
            riskScore: 45.2,
            nextMaintenanceEstimate: "2025-07-18",
            alertStatus: "Warning",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "SK3823",
            model: "Boeing 737-900",
            flightHoursSinceLastMaintenance: 340,
            engineTemperature: 492,
            vibrationLevel: 1.6,
            hydraulicPressure: 3150,
            brakeWearPercent: 32,
            oilParticleCount: 720,
            weatherStressIndex: 6.1,
            aircraftAgeYears: 6,
            flightCycles: 5890,
            mtbf: 520,
            lastFailureDate: "2023-10-28",
            lastFailureType: "Landing Gear",
            failureHistory: [
                { date: "2023-10-28", type: "Landing Gear", severity: "minor" },
                { date: "2023-06-12", type: "Hydraulic", severity: "minor" }
            ],
            overallStatus: "normal",
            riskScore: 28.7,
            nextMaintenanceEstimate: "2025-08-25",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "LA9571",
            model: "Airbus A350-900",
            flightHoursSinceLastMaintenance: 180,
            engineTemperature: 478,
            vibrationLevel: 1.3,
            hydraulicPressure: 3250,
            brakeWearPercent: 22,
            oilParticleCount: 380,
            weatherStressIndex: 4.8,
            aircraftAgeYears: 4,
            flightCycles: 3450,
            mtbf: 650,
            lastFailureDate: null,
            lastFailureType: null,
            failureHistory: [],
            overallStatus: "normal",
            riskScore: 15.3,
            nextMaintenanceEstimate: "2025-10-12",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "AA7291",
            model: "Boeing 767-300",
            flightHoursSinceLastMaintenance: 670,
            engineTemperature: 508,
            vibrationLevel: 2.2,
            hydraulicPressure: 2800,
            brakeWearPercent: 78,
            oilParticleCount: 1100,
            weatherStressIndex: 7.8,
            aircraftAgeYears: 11,
            flightCycles: 9870,
            mtbf: 290,
            lastFailureDate: "2024-01-15",
            lastFailureType: "Engine",
            failureHistory: [
                { date: "2024-01-15", type: "Engine", severity: "major" },
                { date: "2023-09-30", type: "Brake System", severity: "minor" },
                { date: "2023-05-18", type: "Avionics", severity: "minor" }
            ],
            overallStatus: "warning",
            riskScore: 62.1,
            nextMaintenanceEstimate: "2025-04-08",
            alertStatus: "Warning",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "BA8817",
            model: "Airbus A380",
            flightHoursSinceLastMaintenance: 290,
            engineTemperature: 495,
            vibrationLevel: 1.4,
            hydraulicPressure: 3300,
            brakeWearPercent: 28,
            oilParticleCount: 580,
            weatherStressIndex: 5.5,
            aircraftAgeYears: 9,
            flightCycles: 8230,
            mtbf: 580,
            lastFailureDate: "2023-08-05",
            lastFailureType: "Hydraulic",
            failureHistory: [
                { date: "2023-08-05", type: "Hydraulic", severity: "minor" },
                { date: "2023-03-22", type: "Landing Gear", severity: "minor" }
            ],
            overallStatus: "normal",
            riskScore: 22.8,
            nextMaintenanceEstimate: "2025-09-30",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "AF8764",
            model: "Boeing 747-8",
            flightHoursSinceLastMaintenance: 420,
            engineTemperature: 502,
            vibrationLevel: 1.7,
            hydraulicPressure: 3050,
            brakeWearPercent: 55,
            oilParticleCount: 890,
            weatherStressIndex: 6.9,
            aircraftAgeYears: 7,
            flightCycles: 7120,
            mtbf: 420,
            lastFailureDate: "2023-11-08",
            lastFailureType: "Avionics",
            failureHistory: [
                { date: "2023-11-08", type: "Avionics", severity: "major" },
                { date: "2023-07-14", type: "Engine", severity: "minor" }
            ],
            overallStatus: "warning",
            riskScore: 48.9,
            nextMaintenanceEstimate: "2025-07-05",
            alertStatus: "Warning",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "WN2726",
            model: "Airbus A220-300",
            flightHoursSinceLastMaintenance: 75,
            engineTemperature: 468,
            vibrationLevel: 1.0,
            hydraulicPressure: 3180,
            brakeWearPercent: 15,
            oilParticleCount: 320,
            weatherStressIndex: 3.9,
            aircraftAgeYears: 2,
            flightCycles: 2340,
            mtbf: 750,
            lastFailureDate: null,
            lastFailureType: null,
            failureHistory: [],
            overallStatus: "normal",
            riskScore: 8.7,
            nextMaintenanceEstimate: "2025-12-20",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "AC1756",
            model: "Boeing 737 MAX 8",
            flightHoursSinceLastMaintenance: 890,
            engineTemperature: 515,
            vibrationLevel: 2.3,
            hydraulicPressure: 2750,
            brakeWearPercent: 82,
            oilParticleCount: 1350,
            weatherStressIndex: 8.5,
            aircraftAgeYears: 6,
            flightCycles: 6780,
            mtbf: 280,
            lastFailureDate: "2024-02-10",
            lastFailureType: "Brake System",
            failureHistory: [
                { date: "2024-02-10", type: "Brake System", severity: "critical" },
                { date: "2023-12-20", type: "Engine", severity: "major" },
                { date: "2023-08-08", type: "Hydraulic", severity: "minor" }
            ],
            overallStatus: "critical",
            riskScore: 85.2,
            nextMaintenanceEstimate: "2025-02-28",
            alertStatus: "Critical",
            maintenanceStatus: "Overdue"
        },
        {
            tailNumber: "SA7667",
            model: "Airbus A320neo",
            flightHoursSinceLastMaintenance: 150,
            engineTemperature: 482,
            vibrationLevel: 1.5,
            hydraulicPressure: 3120,
            brakeWearPercent: 20,
            oilParticleCount: 450,
            weatherStressIndex: 4.6,
            aircraftAgeYears: 3,
            flightCycles: 3890,
            mtbf: 680,
            lastFailureDate: null,
            lastFailureType: null,
            failureHistory: [],
            overallStatus: "normal",
            riskScore: 16.2,
            nextMaintenanceEstimate: "2025-11-15",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "TG8482",
            model: "Boeing 787-10",
            flightHoursSinceLastMaintenance: 280,
            engineTemperature: 489,
            vibrationLevel: 1.3,
            hydraulicPressure: 3220,
            brakeWearPercent: 35,
            oilParticleCount: 620,
            weatherStressIndex: 5.2,
            aircraftAgeYears: 5,
            flightCycles: 4560,
            mtbf: 590,
            lastFailureDate: "2023-09-12",
            lastFailureType: "Landing Gear",
            failureHistory: [
                { date: "2023-09-12", type: "Landing Gear", severity: "minor" }
            ],
            overallStatus: "normal",
            riskScore: 24.1,
            nextMaintenanceEstimate: "2025-08-18",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "TG5949",
            model: "Airbus A330neo",
            flightHoursSinceLastMaintenance: 720,
            engineTemperature: 510,
            vibrationLevel: 2.0,
            hydraulicPressure: 2880,
            brakeWearPercent: 68,
            oilParticleCount: 1150,
            weatherStressIndex: 7.5,
            aircraftAgeYears: 8,
            flightCycles: 7230,
            mtbf: 340,
            lastFailureDate: "2023-12-25",
            lastFailureType: "Engine",
            failureHistory: [
                { date: "2023-12-25", type: "Engine", severity: "major" },
                { date: "2023-08-30", type: "Hydraulic", severity: "minor" }
            ],
            overallStatus: "warning",
            riskScore: 58.7,
            nextMaintenanceEstimate: "2025-05-12",
            alertStatus: "Warning",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "SK7047",
            model: "Boeing 777-200",
            flightHoursSinceLastMaintenance: 950,
            engineTemperature: 525,
            vibrationLevel: 2.5,
            hydraulicPressure: 2600,
            brakeWearPercent: 92,
            oilParticleCount: 1550,
            weatherStressIndex: 9.2,
            aircraftAgeYears: 14,
            flightCycles: 14560,
            mtbf: 160,
            lastFailureDate: "2024-01-25",
            lastFailureType: "Brake System",
            failureHistory: [
                { date: "2024-01-25", type: "Brake System", severity: "critical" },
                { date: "2023-11-18", type: "Engine", severity: "critical" },
                { date: "2023-07-05", type: "Avionics", severity: "major" },
                { date: "2023-04-12", type: "Hydraulic", severity: "major" }
            ],
            overallStatus: "critical",
            riskScore: 91.8,
            nextMaintenanceEstimate: "2025-01-30",
            alertStatus: "Critical",
            maintenanceStatus: "Overdue"
        },
        {
            tailNumber: "AC5785",
            model: "Airbus A321neo",
            flightHoursSinceLastMaintenance: 110,
            engineTemperature: 476,
            vibrationLevel: 1.2,
            hydraulicPressure: 3160,
            brakeWearPercent: 18,
            oilParticleCount: 410,
            weatherStressIndex: 4.1,
            aircraftAgeYears: 2,
            flightCycles: 2980,
            mtbf: 710,
            lastFailureDate: null,
            lastFailureType: null,
            failureHistory: [],
            overallStatus: "normal",
            riskScore: 11.9,
            nextMaintenanceEstimate: "2025-12-05",
            alertStatus: "Normal",
            maintenanceStatus: "Scheduled"
        },
        {
            tailNumber: "SQ7108",
            model: "Boeing 737-700",
            flightHoursSinceLastMaintenance: 580,
            engineTemperature: 505,
            vibrationLevel: 2.1,
            hydraulicPressure: 2920,
            brakeWearPercent: 72,
            oilParticleCount: 1080,
            weatherStressIndex: 7.1,
            aircraftAgeYears: 10,
            flightCycles: 8920,
            mtbf: 310,
            lastFailureDate: "2023-10-15",
            lastFailureType: "Engine",
            failureHistory: [
                { date: "2023-10-15", type: "Engine", severity: "major" },
                { date: "2023-06-28", type: "Brake System", severity: "minor" },
                { date: "2023-03-14", type: "Avionics", severity: "minor" }
            ],
            overallStatus: "warning",
            riskScore: 65.4,
            nextMaintenanceEstimate: "2025-06-20",
            alertStatus: "Warning",
            maintenanceStatus: "Scheduled"
        }
    ];

    return {
        getAircraftData: function() {
            return aircraftFleetData;
        },
        
        createModel: function() {
            return new JSONModel(aircraftFleetData);
        }
    };
}); 